
// // app/layout.tsx
// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Inter } from "next/font/google";
// import Providers from "@/components/Providers";
// import Appbar from "@/components/Appbar";
// import './globals.css';
// import SigninButton from "@/components/SigninButton";
// import { cn } from "@/lib/utils";

// const inter = Inter({subsets:['latin'],variable:'--font-sans'});


// // Load fonts with strategy: "class" for consistent SSR
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning className={cn("font-sans", inter.variable)}>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* <Providers>
//           <Appbar /> */}
//           {children}
//         {/* </Providers> */}
//         {/* <Providers>
//           <SigninButton/>
//         </Providers> */}
//       </body>
//     </html>
//   );
// }

// // import type { Metadata } from "next"; import { Geist, Geist_Mono } from "next/font/google"; import "./globals.css"; const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"], }); const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"], }); export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app", }; export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) { return ( <html lang="en"> <body className={${geistSans.variable} ${geistMono.variable} antialiased} > {children} </body> </html> ); }



// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import Providers from "@/components/Providers";
import { getServerSession } from "next-auth";
import  Footer  from "@/components/Footer";
import './globals.css'
import { TooltipProvider } from "@/components/ui/tooltip"

// Load fonts with strategy: "class" for consistent SSR
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hotel Reservation System",
  description: "Generated by create next app",
};
export default async function RootLayout({children,}: {children: React.ReactNode;}) {

    const session = await getServerSession();

  return (

        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} font-normal`}
          >
            
              <Providers session={session}>
                  <TooltipProvider>{children}</TooltipProvider>
                <Footer/>
              </Providers> 

              <Toaster/>
          </body>
        </html>
      );
}
