
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import Providers from "@/components/Providers";
import { getServerSession } from "next-auth";
import  Footer  from "@/components/Footer";
import './globals.css'
import { TooltipProvider } from "@/components/ui/tooltip"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hotel Reservation System",
  description: "Generated by create next app",
};
export default async function RootLayout({children,}: {children: React.ReactNode;}) {

    const session = await getServerSession();

  return (

        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} font-normal`}
          >
            
              <Providers session={session}>
                  <TooltipProvider>{children}</TooltipProvider>
                <Footer/>
              </Providers> 

              <Toaster/>
          </body>
        </html>
      );
}
